package com.hero.middleware.dto.fanwei;

import lombok.Data;

import java.io.Serializable;

@Data
public class FanWeicontractBoardDto implements Serializable {

    private static final long serialVersionUID = 1L;

    /** 泛微名称-合同主表 */
    private Object contract_board;
    /** 泛微名称-来源表 */
    private Object source_table;
    /** 泛微名称-id */
    private Object old_main_id;
    /** 泛微名称-合同标题 */
    private Object contract_name;
    /** 泛微名称-合同编号 */
    private Object contract_code;
    /** 泛微名称-关联框架协议/合同编号 */
    private Object framework_contract_code;
    /** 泛微名称-关联框架协议/合同标题 */
    private Object framework_contract_name;
    /** 泛微名称-合同录入人 */
    private Object applicant_name;
    /** 泛微名称-合同录入人工号 */
    private Object applicant_workcode;
    /** 泛微名称-合同执行人员 */
    private Object executor_name;
    /** 泛微名称-合同执行人工号 */
    private Object executor_workcode;
    /** 泛微名称-订单名称 */
    private Object order_name;
    /** 泛微名称-uf_htk.ddbhsc */
    private Object order_code_main;
    /** 泛微名称-uf_htk_dt1/5/6/7.订单号 */
    private Object order_code_detail;
    /** 泛微名称-成本中心 */
    private Object cost_center_name;
    /** 泛微名称-uf_htk.xmzhksrq */
    private Object order_period_main_start;
    /** 泛微名称-uf_htk.xmzhjsrq */
    private Object order_period_main_end;
    /** 泛微名称-uf_htk_dt1/5/6/7.ksrq */
    private Object order_period_detail_start;
    /** 泛微名称-uf_htk_dt1/5/6/7.jsrq */
    private Object order_period_detail_end;
    /** 泛微名称-合同二级类型 */
    private Object contract_type;
    /** 泛微名称-uf_xmkp.xmjl */
    private Object project_manager_xmkp_name;
    /** 泛微名称-uf_xmkp.xmjl */
    private Object project_manager_xmkp_workcode;
    /** 泛微名称-无 */
    private Object project_sponsor_name;
    /** 泛微名称-无 */
    private Object project_sponsor_workcode;
    /** 泛微名称-无 */
    private Object purchase_apply;
    /** 泛微名称-无 */
    private Object special_category;
    /** 泛微名称-主播卡片地址 */
    private Object address;
    /** 泛微名称-uf_htk.htyxqqssj */
    private Object valid_start_time;
    /** 泛微名称-uf_htk.htyxqjzsj */
    private Object valid_end_time;
    /** 泛微名称-无 */
    private Object loan_start_time;
    /** 泛微名称-无 */
    private Object loan_end_time;
    /** 泛微名称-无 */
    private Object need_acceptance;
    /** 泛微名称-合同类型/合同预计收入/合同预计支出 */
    private Object income_expense_type;
    /** 泛微名称-无 */
    private Object pricing_method;
    /** 泛微名称-合同预计收入/合同预计支出/合同金额 */
    private Object contract_total_amount;
    /** 泛微名称-无 */
    private Object estimated_amount;
    /** 泛微名称-无 */
    private Object pricing_description;
    /** 泛微名称-合同有效期起始时间/合同有效期截止时间 */
    private Object term_type;
    /** 泛微名称-uf_htk.htyxqqssj */
    private Object contract_period_start;
    /** 泛微名称-uf_htk.htyxqjzsj */
    private Object contract_period_end;
    /** 泛微名称-无 */
    private Object term_description;
    /** 泛微名称-合同情况备注/合同摘要 */
    private Object contract_description;
    /** 泛微名称-合同预计收入/合同预计支出 */
    private Object income_expense_both_flag;
    /** 泛微名称-无 */
    private Object major_contract_flag;
    /** 泛微名称-无 */
    private Object multi_tax_rate_flag;
    /** 泛微名称-无 */
    private Object bank_charge_bearer;
    /** 泛微名称-无 */
    private Object anti_bribery_flag;
    /** 泛微名称-无 */
    private Object invoice_type;
    /** 泛微名称-无 */
    private Object income_currency;
    /** 泛微名称-无 */
    private Object income_rate;
    /** 泛微名称-合同预计收入 */
    private Object income_amount;
    /** 泛微名称-合同预计收入 */
    private Object income_amount_cny;
    /** 泛微名称-无 */
    private Object income_tax_rate;
    /** 泛微名称-无 */
    private Object income_tax_amount;
    /** 泛微名称-无 */
    private Object expense_currency;
    /** 泛微名称-无 */
    private Object expense_rate;
    /** 泛微名称-合同预计支出 */
    private Object expense_amount;
    /** 泛微名称-合同预计支出 */
    private Object expense_amount_cny;
    /** 泛微名称-无 */
    private Object expense_tax_rate;
    /** 泛微名称-无 */
    private Object expense_tax_amount;
    /** 泛微名称-无 */
    private Object expense_amount_excluding_tax;
    /** 泛微名称-无 */
    private Object deposit_amount;
    /** 泛微名称-无 */
    private Object guarantee_amount;
    /** 泛微名称-无 */
    private Object stamp_tax;
    /** 泛微名称-无 */
    private Object stamp_tax_type;
    /** 泛微名称-合同用印范围 */
    private Object our_party;
    /** 泛微名称-合同客户/合同供应商/主播姓名/主播昵称 */
    private Object counterparty;
    /** 泛微名称-合同供应商 */
    private Object supplier_name;
    /** 泛微名称-合同供应商/税号 */
    private Object supplier_tax_no;
    /** 泛微名称-主播姓名 */
    private Object anchor_name;
    /** 泛微名称-主播昵称 */
    private Object anchor_nick_name;
    /** 泛微名称-主播ID */
    private Object anchor_room_or_id;
    /** 泛微名称-主播身份证号码 */
    private Object anchor_id_no;
    /** 泛微名称-战队名称 */
    private Object team_name;
    /** 泛微名称-无 */
    private Object revised_income_amount;
    /** 泛微名称-无 */
    private Object revised_expense_amount;
    /** 泛微名称-无 */
    private Object revised_deposit_amount;
    /** 泛微名称-无 */
    private Object revised_guarantee_amount;
    /** 泛微名称-礼物基础分成比例 */
    private Object gift_basic_share_ratio;
    /** 泛微名称-官签时长分成比例 */
    private Object official_duration_share_ratio;
    /** 泛微名称-商务分成比例 */
    private Object commercial_share_ratio;
    /** 泛微名称-官签签约金 */
    private Object official_signing_fee;
    /** 泛微名称-官签签约金分成比例 */
    private Object official_signing_fee_share_ratio;
    /** 泛微名称-固定底薪（每月） */
    private Object fixed_base_salary_per_month;
    /** 泛微名称-公司签约金 */
    private Object company_signing_fee;
    /** 泛微名称-备注 */
    private Object other_description;
    /** 泛微名称-签约期限（月） */
    private Object signing_term_months;
    /** 泛微名称-所属平台 */
    private Object platform_name;
    /** 泛微名称-主播简介 */
    private Object anchor_profile;
    /** 泛微名称-预计回本周期（月） */
    private Object estimated_payback_cycle_months;
}
